version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hr_system
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # HR System App
  hr_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_LINK=postgresql://hr_user:hr_password@postgres:5432/hr_system
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FLASK_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./charts:/app/charts

volumes:
  postgres_data:
